sudo: required
dist: trusty
language: r
pandoc_version: 1.19.2.1
install:
  - sudo apt-get install poppler-utils 
  - tlmgr install longtable xecjk filehook unicode-math ucharcat pagecolor babel-german ly1 mweights sourcecodepro sourcesanspro 
before_script:
  - cd examples
script:
  - sh build.sh